seed: 42

dataset_root: './dataset'
model_root: './models'
log_root: './logs'
pic_root: './pics'

rpm:
  - 600
  - 800
  - 1000
  - 1200
  - 1400
  - 1600
      
# data labels
label:
  H: 0
  U1: 1
  U2: 2
  U3: 3
  L: 4
  M1: 5
  M2: 6
  M3: 7

# input data length and overlap
sample_size: 2048
overlap: 1024

# learning parameters
batch_size: 128
learning_rate: 1e-3
epoch: 100