seed: 42

dataset_root_uos: './dataset'
dataset_root_st: './data_st'
model_root: './models'
model_root_st: './models_st'
log_root: './logs'
log_root_st: './logs_st'
pic_root: './pics'
pic_root_st: './pics_st'

sampling_rate: 16000

rpm:
  - 600
  - 800
  - 1000
  - 1200
  - 1400
  - 1600
      
# data labels
label:
  H: 0
  L: 1
  M1: 2
  M2: 3
  M3: 4
  U1: 5
  U2: 6
  U3: 7

# input data length and overlap (no overlap if samplre_size == overlap)
sample_size: 2048
overlap: 2048

# learning parameters
batch_size: 128
learning_rate: 1e-3
epoch: 100